version: '2'

services:
  db:
    image: postgres:9.5.12-alpine
    volumes:
      - ./volumes/db3:/var/lib/postgresql/data
    ports:
      - 54320:5432  
  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8100:8000
    depends_on:
      - db