# Generated by Django 2.0.2 on 2018-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(default='nome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='nome', max_length=255),
            preserve_default=False,
        ),
    ]
