# Generated by Django 2.0.2 on 2018-03-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180312_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement_value', models.FloatField()),
                ('unit_of_measurement', models.CharField(max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='measurement_value',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='sensormeasure',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='api.Sensor'),
        ),
    ]
