# Generated by Django 2.0.2 on 2018-03-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180312_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormeasure',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.Sensor'),
        ),
    ]
