# Generated by Django 2.0.2 on 2018-03-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180312_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_type',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.SensorType'),
            preserve_default=False,
        ),
    ]
