# Generated by Django 2.0.2 on 2018-03-28 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20180312_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('identify', models.CharField(max_length=255)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colectors', to='api.Local')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='local',
            new_name='colector',
        ),
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
